"""add current_page column to Article

Revision ID: 364deb8f45bf
Revises: 6721e4fb387e
Create Date: 2023-05-05 16:49:12.501535

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '364deb8f45bf'
down_revision = '6721e4fb387e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('current_page', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('current_page')

    # ### end Alembic commands ###
