"""change user-article relationship to one-many

Revision ID: 6721e4fb387e
Revises: 5b4fe4fc9d11
Create Date: 2023-05-05 15:38:31.716940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6721e4fb387e'
down_revision = '5b4fe4fc9d11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_articles')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_articles_user_id_users'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_articles_user_id_users'), type_='foreignkey')
        batch_op.drop_column('user_id')

    op.create_table('user_articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('article_id', sa.INTEGER(), nullable=True),
    sa.Column('current_page', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name='fk_user_articles_article_id_articles'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_user_articles_user_id_users'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
